// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozvoqdkfbtctlvyvdrks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dm9xZGtmYnRjdGx2eXZkcmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5OTI2NjgsImV4cCI6MjA1MTU2ODY2OH0.hVMANGoBIIhU2yUCoRiD7vSdSVq9uxfZtZYMMgW_31A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);